import { StateGraph, START, END, MemorySaver, Annotation } from "@langchain/langgraph";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { prisma } from "../index";

const AgentStateAnnotation = Annotation.Root({
  incidentId: Annotation<string>(),
  context: Annotation<string>(),
  analysis: Annotation<string>(),
  fixPlan: Annotation<string>(),
  patch: Annotation<string>(),
  status: Annotation<string>(),
});

const llm = new ChatGoogleGenerativeAI({
  model: "gemini-1.5-pro",
  apiKey: process.env.GEMINI_API_KEY || "dummy",
});

async function investigate(state: typeof AgentStateAnnotation.State): Promise<Partial<typeof AgentStateAnnotation.State>> {
  const incident = await prisma.incident.findUnique({ where: { id: state.incidentId } });
  
  const response = await llm.invoke(`
    You are an AI Incident Responder.
    Investigate this incident: ${incident?.title}
    Description: ${incident?.description}
    Provide a detailed analysis of the root cause.
  `);

  return { analysis: response.content as string, status: "investigated" };
}

async function planFix(state: typeof AgentStateAnnotation.State): Promise<Partial<typeof AgentStateAnnotation.State>> {
  const response = await llm.invoke(`
    Based on the analysis: ${state.analysis}
    Propose a step-by-step fix plan to resolve the root cause.
  `);
  
  return { fixPlan: response.content as string, status: "planned" };
}

async function generatePatch(state: typeof AgentStateAnnotation.State): Promise<Partial<typeof AgentStateAnnotation.State>> {
  const response = await llm.invoke(`
    Based on the plan: ${state.fixPlan}
    Provide the exact code patch to fix the issue. Only output the patch block.
  `);
  
  await prisma.fix.create({
    data: {
      incidentId: state.incidentId,
      description: "Generated by Sentinel AI Workflow",
      patch: response.content as string,
      status: "generated",
    }
  });

  return { patch: response.content as string, status: "resolved" };
}

const builder = new StateGraph(AgentStateAnnotation)
  .addNode("investigate", investigate)
  .addNode("planFix", planFix)
  .addNode("generatePatch", generatePatch)
  .addEdge(START, "investigate")
  .addEdge("investigate", "planFix")
  .addEdge("planFix", "generatePatch")
  .addEdge("generatePatch", END);

export const graph = builder.compile({ checkpointer: new MemorySaver() });

export async function runAgentWorkflow(incidentId: string) {
  const run = await prisma.agentRun.create({
    data: { incidentId, status: "running" }
  });

  try {
    const config = { configurable: { thread_id: run.id } };
    const initialState = { incidentId, context: "", analysis: "", fixPlan: "", patch: "", status: "started" };
    
    await graph.invoke(initialState, config);
    
    await prisma.agentRun.update({
      where: { id: run.id },
      data: { status: "completed", endedAt: new Date() }
    });
    
    await prisma.incident.update({
      where: { id: incidentId },
      data: { status: "resolving" }
    });
  } catch (error) {
    console.error("Agent workflow failed:", error);
    await prisma.agentRun.update({
      where: { id: run.id },
      data: { status: "failed", endedAt: new Date() }
    });
  }
}
